AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  cdkInit:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: cdkInit/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 900
      Role:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/lambda_basic_execute_role'